spring:
  application:
    name: apigatewayserver
  profiles:
    include: jwt
  cloud:
    gateway:
      routes:

        - id: CapstoneUser
          uri: lb://Capstone
          predicates:
            - Path=/api/users/login
            - Method=POST
        - id: CapstoneUser
          uri: lb://Capstone
          predicates:
            - Path=/api/users/register
            - Method=POST
        - id: CapstoneUser
          uri: lb://Capstone
          predicates:
            - Path=/api/users/**
          filters:
            - AuthorizationHeaderFilter
        - id: CapstoneYoutube
          uri: lb://youtube-service
          predicates:
            - Path=/api/youtube/**
#          filters:
#            - AuthorizationHeaderFilter




management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000
