spring:
  application:
    name: Capstone
  profiles:
    include: jwt
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/capstone
    username: root
    password: tkfka5470
  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
      operations-sorter: alpha
      tags-sorter: alpha
      path: /swagger-ui.html
      disable-swagger-default-url: true
      display-query-params-without-oauth2: true
      doc-expansion: none
    paths-to-match:
      - /api/**
logging:
  level:
    org.springframework.security: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 0
